spring:
  cloud:
    gateway:
      #路由配置
      routes:
        #唯一标识符
        - id: sandbox
          uri: lb://sandbox
          #路由断言
          predicates:
            - Path=/sandbox/**
      discovery:
        locator:
          enabled: true
knife4j:
  gateway:
    # 开起网关聚合文档
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认 default 分组
    strategy: discover
    # 服务发现
    discover:
      enabled: true
      version: openapi3
#      excluded-services: ${spring.application.name}